---
version: "3.3"
networks:
  default:
    name: 'proxy_network'
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: always
    environment:
      - HOMEPAGE_VAR_PROXMOX_PASS=${PROXMOX_PASS}
      - HOMEPAGE_VAR_PROXMOX_USER=${PROXMOX_USER}
      - HOMEPAGE_VAR_PLEX_TOKEN=${PLEX_TOKEN}
      - HOMEPAGE_VAR_OVERSEERR_TOKEN=${OVERSEERR_TOKEN}
      - HOMEPAGE_VAR_SONARR_TOKEN=${SONARR_TOKEN}
      - HOMEPAGE_VAR_RADARR_TOKEN=${RADARR_TOKEN}
      - HOMEPAGE_VAR_LIDARR_TOKEN=${LIDARR_TOKEN}
      - HOMEPAGE_VAR_PROWLARR_TOKEN=${PROWLARR_TOKEN}
      - HOMEPAGE_VAR_QBITTORRENT_USER=${QBITTORRENT_USER}
      - HOMEPAGE_VAR_QBITTORRENT_PASS=${QBITTORRENT_PASS}
      - HOMEPAGE_VAR_SABNZBD_TOKEN=${SABNZBD_TOKEN}
      - HOMEPAGE_VAR_OMADA_USER=${OMADA_USER}
      - HOMEPAGE_VAR_OMADA_PASS=${OMADA_PASS}
      - HOMEPAGE_VAR_PIHOLE_TOKEN=${PIHOLE_TOKEN}
