---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Hypervisors:
    - Proxmox:
        href: https://proxmox.imkumpy.in/
        widget:
            type: proxmox
            url: https://proxmox.imkumpy.in
            username: "{{ HOMEPAGE_VAR_PROXMOX_USER}}"
            password: "{{ HOMEPAGE_VAR_PROXMOX_PASS }}"

    - Proxmox-Backup:
        href: https://proxmox-backup.imkumpy.in:8007/

    - Unraid:
        href: http://unraid.imkumpy.in/

- Dockerhost:
    - Caddy:
        description: Reverse Proxy
        server: my-docker
        container: caddy

- General Services:
    - Syncthing Server:
        href: https://syncthing.imkumpy.in:8384/
    - Zabbix:
        href: http://zabbix.imkumpy.in/zabbix/
    - GitLab:
        href: https://git.imkumpy.in/
    - ArgoCD:
        href: https://argocd.imkumpy.in/
    - Grafana:
        href: https://grafana.imkumpy.in/
    - Alertmanager:
        href: https://alertmanager.imkumpy.in/

- Media Management:
    - Plex:
        href: http://unraid.imkumpy.in:32400/
        widget:
          type: plex
          url: http://unraid.imkumpy.in:32400
          key: "{{ HOMEPAGE_VAR_PLEX_TOKEN }}"
    - Overseerr:
        href: https://requests.imkumpy.com/
        widget:
          type: overseerr
          url: http://unraid.imkumpy.in:5055
          key: "{{ HOMEPAGE_VAR_OVERSEERR_TOKEN }}"
    - Sonarr:
        href: http://unraid.imkumpy.in:8989/
        widget:
          type: sonarr
          url: http://unraid.imkumpy.in:8989
          key: "{{ HOMEPAGE_VAR_SONARR_TOKEN }}"
    - Radarr:
        href: http://unraid.imkumpy.in:7878/
        widget:
          type: radarr
          url: http://unraid.imkumpy.in:7878
          key: "{{ HOMEPAGE_VAR_RADARR_TOKEN }}"
    - Lidarr:
        href: http://unraid.imkumpy.in:8686/
        widget:
          type: lidarr
          url: http://unraid.imkumpy.in:8686
          key: "{{ HOMEPAGE_VAR_LIDARR_TOKEN }}"
    - Prowlarr:
        href: http://unraid.imkumpy.in:9696/
        widget:
          type: prowlarr
          url: http://unraid.imkumpy.in:9696
          key: "{{ HOMEPAGE_VAR_PROWLARR_TOKEN }}"
    - qBittorrent:
        href: http://unraid.imkumpy.in:8080/
        widget:
          type: qbittorrent
          url: http://unraid.imkumpy.in:8080
          username: "{{ HOMEPAGE_VAR_QBITTORRENT_USER }}"
          password: "{{ HOMEPAGE_VAR_QBITTORRENT_PASS }}"
    - SABnzbd:
        href: http://192.168.0.104:8081/
        widget:
          type: sabnzbd
          url: http://192.168.0.104:8081
          key: "{{ HOMEPAGE_VAR_SABNZBD_TOKEN }}"

- Network:
    - Omada:
        href: https://omada.imkumpy.in/
        widget:
            type: omada
            url: https://omada.imkumpy.in
            username: "{{ HOMEPAGE_VAR_OMADA_USER }}"
            password: "{{ HOMEPAGE_VAR_OMADA_PASS }}"
            site: Default
    - PiHole (Active VIP):
        href: http://pihole.imkumpy.in/admin/
        widget:
          type: pihole
          url: http://pihole.imkumpy.in
          key: "{{ HOMEPAGE_VAR_PIHOLE_TOKEN }}"
    - PiHole (ns1):
        href: http://ns1.imkumpy.in/admin/
        widget:
          type: pihole
          url: http://ns1.imkumpy.in
          key: "{{ HOMEPAGE_VAR_PIHOLE_TOKEN }}"
    - PiHole (ns2):
        href: http://ns2.imkumpy.in/admin/
        widget:
          type: pihole
          url: http://ns2.imkumpy.in
          key: "{{ HOMEPAGE_VAR_PIHOLE_TOKEN }}"
